services:
  db:
    image: postgres:18
    container_name: postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tdapp
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d dev_database" ]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=0
      - LOCALSTACK_AUTH_TOKEN=ls-Nipu2233-RoMe-DiRU-DutO-LuqOzAXe106a
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init_s3.sh:/etc/localstack/init/ready.d/init_s3.sh"

  db_migration:
    image: tdapp:local
    container_name: db_migration
    command: [ "./tdapp", "migrate" ]
    depends_on:
      db:
        condition: service_healthy
    environment:
      TDAPP_DB_HOST: db
      TDAPP_DB_USER: dev
      TDAPP_DB_PASSWORD: dev
      TDAPP_DB_NAME: tdapp
      TDAPP_DB_SSLMODE: disable

  tdapp_api:
    image: tdapp:local
    container_name: tdapp_api
    command: [ "./tdapp", "api" ]
    depends_on:
      db:
        condition: service_healthy
    environment:
      TDAPP_DB_HOST: db
      TDAPP_DB_USER: dev
      TDAPP_DB_PASSWORD: dev
      TDAPP_DB_NAME: tdapp
      TDAPP_DB_SSLMODE: disable

  tdapp_watcher:
    image: tdapp:local
    container_name: tdapp_watcher
    command: [ "./tdapp", "watcher" ]
    depends_on:
      db:
        condition: service_healthy
    environment:
      TDAPP_DB_HOST: db
      TDAPP_DB_USER: dev
      TDAPP_DB_PASSWORD: dev
      TDAPP_DB_NAME: tdapp
      TDAPP_DB_SSLMODE: disable