services:
  db:
    image: postgres:18
    container_name: postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tdapp
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d dev_database" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db_migration:
    build:
      context: ../
      dockerfile: ./docker/tdapp_local.DockerFile
    container_name: db_migration
    command: [ "./tdapp", "migrate" ]
    depends_on:
      db:
        condition: service_healthy
    environment:
      TDAPP_DB_HOST: db
      TDAPP_DB_USER: dev
      TDAPP_DB_PASSWORD: dev
      TDAPP_DB_NAME: tdapp
      TDAPP_DB_SSLMODE: disable