@startuml
'https://plantuml.com/sequence-diagram


[*] --> todo
todo --> processing
processing --> completed
processing --> todo
processing --> failed
todo --> cancelled
processing --> cancelled
completed --> [*]
failed --> [*]
cancelled --> [*]
@enduml
